services:
  server:
    image: "signalrchatroomserver:prod"
    environment:
      - DB_CONNECTION=Host=db;Port=5433;Database=postgres;User Id=postgres;Password=postgres;
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - app-network

  db:
    image: "ankane/pgvector:v0.4.4"
    command: postgres -c port=5433
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -p 5433"]
      interval: 5s
      start_period: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge